version: '3.3'

volumes:
  disk:
    driver_opts:
      device: /usr/local/data/h-shop-api-gateaway-disk/
      o: bind
      type: none

services:
  build:
    container_name: service-h-shop-api-gateaway
    hostname: host-h-shop-api-gateaway
    build: 
      dockerfile: Dockerfile
      context: .
    image: h-shop-api-gateaway:v1
    volumes:
      - disk:/usr/local/bin/data
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "18880:18880"
    stdin_open: true
    tty: true