version: '3.3'

networks:
  nw_api_test:
    driver: bridge
  
volumes:
  disk_api_test:
    driver_opts:
      device: /usr/local/data/
      o: bind
      type: none

services:
  api_test:
    container_name: api_name_test
    hostname: api_hostname_test
    build: 
      dockerfile: Dockerfile
      context: .
    networks:
      - nw_api_test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - disk_api_test:/usr/local/data
    ports:
      - "18880:18880"
    stdin_open: true
    tty: true